# Runtime environment [develop, staging, live]
cds.environment= develop

# Database Properties
cds.datasource.uri=jdbc:mysql://localhost:3306/
spring.datasource.username=root
spring.datasource.password=root1234

spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# GrpcClient
cds.grpc.authentication.host= localhost
cds.grpc.authentication.port= 5000
