spring.application.name=config

server.port=8760

# Security
spring.security.user.name=admin
spring.security.user.password=malenquilla

# Load configs from local
spring.profiles.active=native

# Set configs paths
spring.cloud.config.server.native.searchLocations=classpath:/configs, classpath:/configs/cloud, classpath:/configs/microservices
