server.name=ai
server.port=7002

# Eureka configs
eureka.url=http://localhost:8761/eureka

# Swagger
openapi.url=/api/v1/ai/openapi.json
docs.url=/api/v1/ai/docs

# API prefix
common.api.prefix=/api/v1