server.port=7000

# Database properties
spring.datasource.url=${cds.datasource.uri}accounts

# App Security Properties
cds.app.jwtSecret= ======================cds.malenquilla===========================
# 1 day
cds.app.accessJwtExpirationMs=86400000
# 30 days
cds.app.refreshJwtExpirationMs=2592000000

#Super Admin
cds.app.super.admin.name=SuperAdmin
cds.app.super.admin.email=dangviettung.works@gmail.com
cds.app.super.admin.password=Tung1234

# Grpc Server
cds.grpc.server.port=5000

#URI
cds.whitelist.uris=/api/v1/auth/login,/api/v1/auth/register,/api/v1/auth/request-activation/*,/api/v1/auth/refresh