server.port=7000

# Database properties
spring.datasource.url=${cds.datasource.uri}accounts

# App Security Properties
cds.app.jwtSecret= ======================cds.malenquilla===========================
# 1 hour
cds.app.accessJwtExpirationMs=3600000
# 7days
cds.app.refreshJwtExpirationMs=604800000