spring.application.name=user

spring.config.import=configserver:http://localhost:8760/
spring.cloud.config.username=admin
spring.cloud.config.password=malenquilla

spring.cloud.config.name=user, common
spring.cloud.config.profile=default
