from grpc import StatusCode
from starlette.status import HTTP_500_INTERNAL_SERVER_ERROR, HTTP_403_FORBIDDEN, HTTP_401_UNAUTHORIZED, \
    HTTP_400_BAD_REQUEST, HTTP_404_NOT_FOUND

grpc_exceptions_dict = {
    StatusCode.INTERNAL: HTTP_500_INTERNAL_SERVER_ERROR,
    StatusCode.PERMISSION_DENIED: HTTP_403_FORBIDDEN,
    StatusCode.UNAUTHENTICATED: HTTP_401_UNAUTHORIZED,
    StatusCode.ABORTED: HTTP_400_BAD_REQUEST,
    StatusCode.NOT_FOUND: HTTP_404_NOT_FOUND
}
